# Generated by Django 4.1.5 on 2023-01-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_modelpost_user_alter_modeltag_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelpost',
            old_name='post_is_published',
            new_name='is_published',
        ),
    ]
