# Generated by Django 4.1.5 on 2023-01-28 21:28

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_post_is_published_modelpost_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpost',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=0.0, force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 300], upload_to='images/%d/%m/%Y/'),
            preserve_default=False,
        ),
    ]
