# Generated by Django 4.1.5 on 2023-01-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_modelpost_fprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='fprice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
