# Generated by Django 4.1.5 on 2023-01-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_modelpost_fprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelpost',
            old_name='fprice',
            new_name='formatted_price',
        ),
        migrations.AddField(
            model_name='modelpost',
            name='formatted_shipping_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modelpost',
            name='formatted_times_split_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
