# Generated by Django 4.1.5 on 2023-01-29 03:02

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_fprice_modelpost_formatted_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to='images/%d/%m/%Y/'),
        ),
    ]
