# Generated by Django 4.1.5 on 2023-01-29 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_modelpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelHighlightPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.modelpost')),
            ],
        ),
    ]
