# Generated by Django 4.1.5 on 2023-01-29 03:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_modelhighlightposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='content',
            field=models.TextField(blank=True, default='...', null=True),
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to='img_posts/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='summary',
            field=models.TextField(blank=True, default='...', null=True),
        ),
        migrations.AlterField(
            model_name='modeltag',
            name='image',
            field=models.ImageField(upload_to='img_tags/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='modeltag',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='ModelStoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_image', models.ImageField(upload_to='img_store/%d/%m/%Y/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
