# Generated by Django 4.1.5 on 2023-01-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_modelpost_content_alter_modelpost_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelpost',
            old_name='image',
            new_name='image_1',
        ),
    ]
