# Generated by Django 4.1.5 on 2023-01-29 21:48

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_image_modelpost_image_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpost',
            name='image_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='img_posts/%d/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='modelpost',
            name='image_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='img_posts/%d/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='modelpost',
            name='image_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='img_posts/%d/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='modelpost',
            name='image_5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='img_posts/%d/%m/%Y/'),
        ),
    ]
