# Generated by Django 4.1.5 on 2023-01-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_modelpost_image_2_modelpost_image_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelpost',
            old_name='tag',
            new_name='tag_1',
        ),
    ]
