# Generated by Django 4.1.5 on 2023-01-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_tag_modelpost_tag_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelpost',
            name='tag_1',
        ),
        migrations.AddField(
            model_name='modelpost',
            name='tags',
            field=models.CharField(default='Exemplo, Exemplo 2', max_length=100),
        ),
        migrations.DeleteModel(
            name='ModelTag',
        ),
    ]
