# Generated by Django 4.1.5 on 2023-01-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_modelpost_times_split_value_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpost',
            name='new_price',
            field=models.FloatField(default=0.0),
        ),
    ]
