# Generated by Django 4.1.5 on 2023-01-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_modelpost_new_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpost',
            name='show_off_price',
            field=models.BooleanField(default=True),
        ),
    ]
