# Generated by Django 4.1.5 on 2023-01-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_rename_price_modelpost_old_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelpost',
            old_name='times_split_price',
            new_name='times_split_num',
        ),
    ]
