# Generated by Django 4.1.5 on 2023-01-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_rename_times_split_price_modelpost_times_split_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelpost',
            old_name='times_split_price_interest',
            new_name='times_split_interest',
        ),
    ]
