# Generated by Django 4.1.5 on 2023-01-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_rename_times_split_price_interest_modelpost_times_split_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelpost',
            old_name='times_split_value_prices',
            new_name='times_split_prices',
        ),
    ]
