# Generated by Django 4.1.5 on 2023-01-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_rename_times_split_value_prices_modelpost_times_split_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelpost',
            name='times_split_prices',
        ),
    ]
