# Generated by Django 4.1.5 on 2023-01-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_modelpost_times_split_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='content',
            field=models.TextField(blank=True, default='...', null=True),
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='summary',
            field=models.CharField(blank=True, default='...', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='tags',
            field=models.CharField(default='Tag 1, Tag 2', max_length=100),
        ),
    ]
