# Generated by Django 4.1.5 on 2023-01-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_modelstoreprofile_social_media_discord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstoreprofile',
            name='show_brand_image_on_nav',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelstoreprofile',
            name='show_brand_name_on_nav',
            field=models.BooleanField(default=False),
        ),
    ]
