# Generated by Django 4.1.5 on 2023-01-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_modelstoreprofile_show_brand_image_on_nav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstoreprofile',
            name='color_theme',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
