# Generated by Django 4.1.5 on 2023-01-31 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_modelstoreprofile_color_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelstoreprofile',
            old_name='color_theme',
            new_name='theme_color',
        ),
    ]
