# Generated by Django 4.1.5 on 2023-01-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_rename_color_theme_modelstoreprofile_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstoreprofile',
            name='theme_contrast_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
