# Generated by Django 4.1.5 on 2023-01-31 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_modelstoreprofile_theme_contrast_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelstoreprofile',
            old_name='theme_color',
            new_name='theme_background_color',
        ),
        migrations.RenameField(
            model_name='modelstoreprofile',
            old_name='theme_contrast_color',
            new_name='theme_text_color',
        ),
    ]
