# Generated by Django 4.1.5 on 2023-01-31 20:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_rename_theme_color_modelstoreprofile_theme_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstoreprofile',
            name='theme_background_color',
            field=colorfield.fields.ColorField(blank=True, default='#39AA62', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='modelstoreprofile',
            name='theme_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
