# Generated by Django 4.1.5 on 2023-01-31 21:24

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_modelstoreprofile_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstoreprofile',
            name='brand_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[80, 40], upload_to='img_store/'),
        ),
    ]
