# Generated by Django 4.1.5 on 2023-01-31 21:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_modelstoreprofile_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstoreprofile',
            name='theme_background_color',
            field=colorfield.fields.ColorField(blank=True, default='#8A42AA', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
