# Generated by Django 4.1.5 on 2023-02-01 00:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0039_profileuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileUser',
            new_name='ModelProfileUser',
        ),
    ]
