# Generated by Django 4.1.5 on 2023-02-01 01:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_modelprofileuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofileuser',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[40, 40], upload_to='img_profile/'),
        ),
    ]
