# Generated by Django 4.1.5 on 2023-02-02 04:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_rename_modelprofileuser_modeluserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstoreprofile',
            name='theme_admin_background_color',
            field=colorfield.fields.ColorField(blank=True, default='#DC3545', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
