# Generated by Django 4.1.5 on 2023-02-02 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0045_modelfavorites_modelbuy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelPost',
            new_name='ModelProduct',
        ),
    ]
