# Generated by Django 4.1.5 on 2023-02-03 00:25

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_modelcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='available_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modelstoreprofile',
            name='theme_admin_background_color',
            field=colorfield.fields.ColorField(blank=True, default='#8F222D', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
