# Generated by Django 4.1.5 on 2023-02-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_rename_modelhighlightposts_modelhighlightproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='max_quantity_per_sale',
            field=models.IntegerField(default=1),
        ),
    ]
