# Generated by Django 4.1.5 on 2023-02-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_modelproduct_max_quantity_per_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='show_available_quantity',
            field=models.BooleanField(default=True),
        ),
    ]
