# Generated by Django 4.1.5 on 2023-02-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_modelproduct_show_available_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcart',
            old_name='product_id',
            new_name='product',
        ),
    ]
