# Generated by Django 4.1.5 on 2023-02-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_rename_product_id_modelcart_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelHighlightProducts',
            new_name='ModelProductHighlight',
        ),
    ]
