# Generated by Django 4.1.5 on 2023-02-03 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_rename_modelcart_modelproductcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproductcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.modelproduct'),
        ),
    ]
