# Generated by Django 4.1.5 on 2023-02-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_alter_modelproductcart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelproductcart',
            name='product_title',
        ),
    ]
