# Generated by Django 4.1.5 on 2023-02-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_modelproductcart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='url_title',
            field=models.CharField(default='Título', max_length=200),
        ),
    ]
