# Generated by Django 4.1.5 on 2023-02-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_modelproduct_url_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelproduct',
            old_name='show_available_quantity',
            new_name='available_quantity_display',
        ),
        migrations.RenameField(
            model_name='modelproduct',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='modelproduct',
            old_name='show_off_price',
            new_name='price_off_display',
        ),
        migrations.RenameField(
            model_name='modelproduct',
            old_name='old_price',
            new_name='price_old',
        ),
        migrations.RenameField(
            model_name='modelproduct',
            old_name='url_title',
            new_name='title_for_url',
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='price_off',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='price_off_pprint',
            field=models.CharField(default='10% OFF', max_length=50),
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='price_old_pprint',
            field=models.CharField(default='R$ 0,00', max_length=50),
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='price_pprint',
            field=models.CharField(default='R$ 0,00', max_length=50),
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='shipping_price_pprint',
            field=models.CharField(default='Frete grátis', max_length=50),
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='times_split_pprint',
            field=models.CharField(default='1x R$ 0,00', max_length=50),
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='times_split_unit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='title_for_card',
            field=models.CharField(default='Título', max_length=200),
        ),
    ]
