# Generated by Django 4.1.5 on 2023-02-05 18:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_rename_show_available_quantity_modelproduct_available_quantity_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstoreprofile',
            name='theme_body_background_color',
            field=colorfield.fields.ColorField(blank=True, default='#ECECEC', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
