# Generated by Django 4.1.5 on 2023-02-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_rename_theme_admin_background_color_modelstoreprofile_theme_admin_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelstoreprofile',
            old_name='theme_body_background_color',
            new_name='theme_background_color',
        ),
    ]
