# Generated by Django 4.1.5 on 2023-02-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_rename_theme_body_background_color_modelstoreprofile_theme_background_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelstoreprofile',
            old_name='theme_text_color',
            new_name='theme_color_text',
        ),
    ]
