# Generated by Django 4.1.5 on 2023-02-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_rename_theme_background_color_modelstoreprofile_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfavorite',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='modelfavorite',
            name='product_title',
        ),
    ]
