# Generated by Django 4.1.5 on 2023-02-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_remove_modelfavorite_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfavorite',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.modelproduct'),
            preserve_default=False,
        ),
    ]
