# Generated by Django 4.1.5 on 2023-02-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_modelproductfavorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelProductFavorite',
        ),
    ]
