# Generated by Django 4.1.5 on 2023-02-06 18:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0071_delete_modelproductfavorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelProductCart',
            new_name='ModelCart',
        ),
    ]
