# Generated by Django 4.1.5 on 2023-02-13 00:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_alter_modelproduct_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproduct',
            name='image_1',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to='img_posts/%d/%m/%Y/'),
        ),
    ]
