# Generated by Django 4.1.5 on 2023-02-13 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_alter_modelproduct_image_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelproduct',
            name='price_off',
        ),
    ]
