# Generated by Django 4.1.5 on 2023-02-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_modelproduct_price_off_alter_modelproduct_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproduct',
            name='price_off',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
