# Generated by Django 4.1.5 on 2023-02-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_alter_modelproduct_price_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcart',
            name='times_split_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelcart',
            name='times_split_pprint',
            field=models.CharField(default='1x R$ 0,00', max_length=50),
        ),
        migrations.AddField(
            model_name='modelcart',
            name='times_split_unit',
            field=models.FloatField(default=0.0),
        ),
    ]
