# Generated by Django 4.1.5 on 2023-02-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_modelcart_times_split_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcart',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
