# Generated by Django 4.1.5 on 2023-02-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_modelcart_total_price_pprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcart',
            name='total_price_pprint',
            field=models.CharField(default='R$ 0,00', max_length=50),
        ),
    ]
