# Generated by Django 4.1.5 on 2023-03-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0081_alter_modelcart_total_price_pprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeluserprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
