# Generated by Django 4.1.5 on 2023-03-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0082_modeluserprofile_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelstoreprofile',
            name='owner',
        ),
    ]
