# Generated by Django 4.1.5 on 2023-03-16 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0083_remove_modelstoreprofile_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProductEdit',
            fields=[
                ('modelproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.modelproduct')),
            ],
            bases=('store.modelproduct',),
        ),
    ]
