# Generated by Django 4.1.5 on 2023-03-16 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0084_modelproductedit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelProductEdit',
        ),
    ]
