# Generated by Django 4.1.5 on 2023-03-16 03:16

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0085_delete_modelproductedit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProductEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Título', max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('price_off_display', models.BooleanField(default=True)),
                ('times_split_num', models.IntegerField(default=0)),
                ('times_split_interest', models.IntegerField(default=0)),
                ('shipping_price', models.FloatField(default=0.0)),
                ('available_quantity', models.IntegerField(default=1)),
                ('available_quantity_display', models.BooleanField(default=True)),
                ('max_quantity_per_sale', models.IntegerField(default=1)),
                ('image_1', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='img_posts/')),
                ('image_2', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='img_posts/')),
                ('image_3', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='img_posts/')),
                ('image_4', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='img_posts/')),
                ('image_5', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='img_posts/')),
                ('summary', models.CharField(blank=True, default='...', max_length=100, null=True)),
                ('content', models.TextField(blank=True, default='...', null=True)),
                ('tags', models.CharField(default='Tag 1, Tag 2', max_length=100)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
