# Generated by Django 4.1.5 on 2023-03-16 16:25

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0086_modelproductedit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstoreprofile',
            name='brand_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[None, 40], upload_to='img_store/'),
        ),
    ]
