# Generated by Django 4.1.5 on 2023-03-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0087_alter_modelstoreprofile_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproduct',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
